//@AUTOHEADER@BEGIN@
/**********************************************************************\
|                          ShoutIRC RadioBot                           |
|           Copyright 2004-2020 Drift Solutions / Indy Sams            |
|        More information available at https://www.shoutirc.com        |
|                                                                      |
|                    This file is part of RadioBot.                    |
|                                                                      |
|   RadioBot is free software: you can redistribute it and/or modify   |
| it under the terms of the GNU General Public License as published by |
|  the Free Software Foundation, either version 3 of the License, or   |
|                 (at your option) any later version.                  |
|                                                                      |
|     RadioBot is distributed in the hope that it will be useful,      |
|    but WITHOUT ANY WARRANTY; without even the implied warranty of    |
|     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the     |
|             GNU General Public License for more details.             |
|                                                                      |
|  You should have received a copy of the GNU General Public License   |
|  along with RadioBot. If not, see <https://www.gnu.org/licenses/>.   |
\**********************************************************************/
//@AUTOHEADER@END@

/*********************************************/
/* Generated by Drift Solutions' make_h 1.00 */
/*      Copyright 2004+ Drift Solutions      */
/*   Generated on Thu Jul 29 14:17:15 2004   */
/*********************************************/

#ifndef __INCLUDE_IRCBOT_BOTAPI_H__
#define __INCLUDE_IRCBOT_BOTAPI_H__

#include "plugins.h"

//int sendsock(int32 netno, char * buf, long datalen);
//char *GetBotNick();

#if defined(IRCBOT_ENABLE_SS)
int GetSSInfo(int32 ssnum, SOUND_SERVER * ss);
void EnableRequests(bool activate);
#endif

void BroadcastMsg(USER_PRESENCE * ut, const char * buf);

#if defined(IRCBOT_ENABLE_IRC)
void SetDoSpam(bool dospam);
void SetDoSpam(bool dospam, int netno, const char * chan);

const char * GetCurrentNick(int32 net);
const char * GetDefaultNick(int32 net);

bool IsIRCSocket(T_SOCKET * sock);
bool LogToChan(const char * buf);
#endif

int32 NumPlugins();
PLUGIN_PUBLIC * GetPlugin(int32 num);

bool IsCommandPrefix(char ch);
char PrimaryCommandPrefix();
const char * FindMagicCommandPrefixes(const char * str);

int SendMessage(int32 toplug, uint32 MsgID, char * data, int32 datalen);

int get_argc();
const char * get_argv(int i);

BOTAPI * GetAPI();

#endif
