//@AUTOHEADER@BEGIN@
/**********************************************************************\
|                          ShoutIRC RadioBot                           |
|           Copyright 2004-2020 Drift Solutions / Indy Sams            |
|        More information available at https://www.shoutirc.com        |
|                                                                      |
|                    This file is part of RadioBot.                    |
|                                                                      |
|   RadioBot is free software: you can redistribute it and/or modify   |
| it under the terms of the GNU General Public License as published by |
|  the Free Software Foundation, either version 3 of the License, or   |
|                 (at your option) any later version.                  |
|                                                                      |
|     RadioBot is distributed in the hope that it will be useful,      |
|    but WITHOUT ANY WARRANTY; without even the implied warranty of    |
|     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the     |
|             GNU General Public License for more details.             |
|                                                                      |
|  You should have received a copy of the GNU General Public License   |
|  along with RadioBot. If not, see <https://www.gnu.org/licenses/>.   |
\**********************************************************************/
//@AUTOHEADER@END@

//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: client.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_client_H__
#define __WDR_client_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "client_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

#define ID_COMBO 1
#define ID_TEXT 2
#define ID_TEXTCTRL 3
#define ID_BUTTON 4
#define ID_CHECKBOX 5
#define ID_TITLE 6
#define ID_LINE 7
#define ID_LISTBOX 8
wxSizer *MainDlg1( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_SERVERS 10002
#define IDC_LOGIN 10003
#define IDC_STATUS_PIC 9
#define IDC_RESPONSE 10004
#define IDC_TITLE 10005
#define IDC_OTHER 10006
#define IDC_DJ_LOGIN 10
#define IDC_DJ_LOG_OUT 11
#define IDC_DO_REQ 12
#define IDC_SHOW_DED_TO 13
#define IDC_CLEAR_REQ 14
#define IDC_REQUESTS 15
extern wxSizer *IDC_ADMIN;
#define IDC_NEXT 16
#define IDC_BCAST 17
#define IDC_DOSPAM 18
#define IDC_DIE 19
#define IDC_RESTART 20
#define IDC_SEND_REQ 21
#define IDC_COUNT 22
#define IDC_FORCE_OFF 23
#define IDC_FORCE_ON 24
#define IDC_PLAY 25
#define IDC_ABOUT 10001
wxSizer *MainDlg2( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_CONLIST 26
#define IDC_BOTNAME 27
#define IDC_BOTIP 28
#define IDC_USERNAME 29
#define IDC_PASS 30
#define IDC_PORT 31
#define IDC_CONNTYPE 32
#define IDC_NEW 33
#define IDC_DELETE 34
#define IDC_CONNECT 35
#define IDC_EXIT 36
wxSizer *ConnectionManager( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_SLOGO 37
#define IDC_UPDATES 38
#define IDC_WIKI 39
#define IDC_WWW 40
#define IDC_DLOGO 41
#define IDC_NAME 42
#define IDC_COMPILED 43
#define IDC_COPYRIGHT 44
#define IDC_LONGABOUT 45
#define IDC_CLOSE 46
wxSizer *AboutBox( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

wxBitmap StatusPics( size_t index );

#endif

// End of generated file
